[app]
name = "Fish"

[app.path]
linux = ["$HOME/.config/fish/functions", "$HOME/.config/fish/completions", "$HOME/.config/fish/fish_variables", "$HOME/.config/fish/config.fish", "$HOME/.config/fish/conf.d"]
macos = ["$HOME/.config/fish/functions", "$HOME/.config/fish/completions", "$HOME/.config/fish/fish_variables", "$HOME/.config/fish/config.fish", "$HOME/.config/fish/conf.d"]
windows = []
