[app]
name = "Tower"

[app.path]
linux = []
macos = ["$HOME/library/application support/com.fournova.tower3", "$HOME/library/preferences/com.fournova.tower.plist", "$HOME/library/application support/tower", "$HOME/library/preferences/com.fournova.tower3.plist"]
windows = []
